pipeline {
    agent any

    stages {
        stage('Checkout Code From Git') {
            steps {
                echo 'Checking out source code...'
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing Python dependencies from root requirement.txt'
                sh '''
                    if [ -d "venv" ]; then
                        echo "Removing old virtual environment..."
                        rm -rf venv
                    fi

                    python3 -m venv venv
                    . venv/bin/activate

                    pip install --upgrade pip
                    pip install -r requirement.txt
                '''
            }
        }

        stage('Run Test Automate') {
            steps {
                echo 'Running automated tests...'
                sh '''
                    . venv/bin/activate
                    robot -d 3_api_testing/output 3_api_testing/tests/users/test_user_api.robot
                '''
            }
        }

        stage('Send Result To Jenkins') {
            steps {
                echo 'Publishing test results...'
                publishHTML(target: [
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: '3_api_testing/output',
                    reportFiles: 'report.html',
                    reportName: 'Robot Framework Report'
                ])
            }
        }
    }

    post {
        always {
            echo 'Build Finished'
        }
    }
}
